apiVersion: apps/v1
kind: Deployment
metadata:
  name: standard-producer
  namespace: stress
  labels:
    app.kubernetes.io/name: standard-producer
    app.kubernetes.io/part-of: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: standard-producer
      app.kubernetes.io/part-of: stress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: standard-producer
        app.kubernetes.io/part-of: stress
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "dedicated"
                    operator: "In"
                    values:
                      - "s2-loadtest"
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "s2-loadtest"
          effect: "NoSchedule"
      containers:
        - name: standard-producer
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          image: ghcr.io/s2-streamstore/stress-stream-rs@sha256:cc82517a97a040f70680c5d469d18ddb7d40b98660f52711b72468f41d0b22a2
          ports:
            - name: metrics
              containerPort: 8000
          env:
            - name: RUST_LOG
              value: "info"
            - name: S2_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: s2-access-token
                  key: s2-access-token
          command:
            - "producer"
            - "--basin"
            - "stress-rs"
            - "--stream"
            - "standard"
            - "--throughput"
            - "1048576"
            - "--avg-record-size"
            - "1024"
            - "--avg-batch-size"
            - "500"
            - "--randomize"
